### ISSUE TITLE
Remove dependency upon "github.com/mbanzon/callbackenv"

### ISSUE THREAD

**Issue by gmlewis** [mbanzon/simplehttp#10]
Would it be possible to either remove the dependency upon "github.com/mbanzon/callbackenv" or make that private repo public?  (Preferably remove it since it is only for a test file.)
Thanks!

**Comment by mbanzon** [comment]
It should work now. I hadn't noticed that the `callbackenv` lib was used here (I deleted it some time ago).

Just out of curiosity: Are you using `simplehttp` as a stand-alone or through the Mailgun library?

**Comment by gmlewis** [comment]
Yes, I was using the Mailgun library.
Thanks!

**Comment by mbanzon** [comment]
Ok - I am planning on removing the dependency from the Mailgun library at some point - that one should be stand alone.
